export type Locale = 'zh' | 'en';
export const content = {
  zh: {
    nav: ['探索操作', '快速入門', '下載'], skip: '跳至教學', language: 'English',
    eyebrow: '為直播、創作與每一次開麥', hero: ['你的聲音，', '由你分流。'],
    intro: '把麥克風、遊戲與語音帶進同一個工作區。加上你的 VST3 外掛，分別決定自己與觀眾聽見什麼。',
    cta: '取得 RoudaMix', explore: '跟著聲音，往下探索', availability: 'Windows 版即將提供',
    scroll: '捲動探索 · 約 1 分鐘', signal: ['麥克風', '遊戲', '語音'],
    chapterLabel: '操作章節', demo: '操作示意 · 非執行中的程式',
    scenes: [
      ['一切聲音，從這裡開始。', '開啟 RoudaMix，讓你的聲音有一個共同的起點。接下來，跟著同一條訊號完成一場直播的音訊配置。', '工作區'],
      ['先選擇，你想處理的聲音。', '在設定的「音訊 / Session」選擇「系統音訊 (WASAPI)」。新增 Audio 軌，將輸入指定為麥克風；遊戲與語音可另用 App 軌擷取。', '裝置與輸入'],
      ['加一點，自己的聲音個性。', '開啟外掛清單，加入已安裝的 VST3。這裡用混響示範，讓聲音多一點空間感。外掛須自行安裝，RoudaMix 不內附此效果。', 'VST3 外掛'],
      ['同一個來源，兩個目的地。', '把輸入軌同時接到監聽與串流輸出。監聽指定耳機並使用 Low Latency；串流指定 CABLE Input，保留 Full PDC 完整處理。', '兩路輸出'],
      ['你聽得清楚，觀眾聽見氛圍。', '開啟混響的 Monitor Bypass。Low-Latency 監聽輸出略過這顆外掛；串流保留混響。兩路聲音，各自合適。', '分流與試聽'],
      ['把完成的聲音，送進直播。', 'RoudaMix 串流送到 CABLE Input。OBS 新增「音訊輸入擷取」，裝置選「CABLE Output」。檢查電平，確認聲音已到達。', '連接 OBS'],
      ['直播之外，也能接著聊。', '在 Discord 的「語音與視訊」選擇 CABLE Output 作為輸入裝置。接受音訊輸入裝置的其他程式，也能沿用這條路徑。', '延伸用途'],
    ],
    monitor: '監聽', stream: '串流', headphones: '耳機', dry: '略過混響', wet: '保留混響',
    audioSoon: '雙路試聽音檔準備中。你仍可繼續閱讀操作示意。', play: '播放試聽', pause: '暫停', audioError: '試聽載入失敗，請稍後重試；教學仍可正常閱讀。', loading: '正在載入試聽…', position: '試聽進度',
    guideLabel: 'QUICK START / 快速入門', guideTitle: '從第一次開啟，\n到第一場直播。', guideIntro: '把這份設定留在手邊。照著走，讓每一路聲音到對的地方。',
    steps: [
      ['解壓，開啟程式', '取得正式 Windows x64 版本後，完整解壓縮，再執行 RoudaMix.exe。可攜版需要 WebView2 Evergreen Runtime；更新時保留 data 資料夾。'],
      ['設定裝置與麥克風', '開啟設定 → 音訊 / Session → 裝置，選擇「系統音訊 (WASAPI)」，必要時按 Start。按「＋ Audio」，在輸入選擇麥克風。App 軌可另外選擇正在發聲的遊戲或語音程式。'],
      ['加入你的 VST3', '先安裝 Windows x64 VST3 外掛，再於 RoudaMix 掃描外掛。從音軌的外掛清單加入效果。示範的 Reverb 是用途標示，不是內建外掛名稱。'],
      ['接好監聽與串流', '在輸入軌的目的地同時選監聽與串流。監聽輸出指定耳機，延遲政策選 Low Latency；串流保留 Full PDC。若要自己略過效果，啟用該外掛的 Monitor Bypass（M）。'],
      ['安裝並設定 VB-CABLE', '從 VB-Audio 官方網站安裝 VB-CABLE，依安裝程式指示重新啟動。RoudaMix 的串流輸出指定 CABLE Input；這是虛擬線材接收聲音的一端。'],
      ['讓 OBS 收到聲音', '在 OBS 來源新增「音訊輸入擷取」，裝置選 CABLE Output。確認電平有反應，錄一小段驗證。避免同時擷取同一麥克風或重複的桌面音訊，造成疊音。Discord 則到「語音與視訊」設定輸入裝置。'],
    ],
    downloadTitle: '下一次開麥，\n讓聲音照你的方式走。', downloadBody: '正式 Windows 版本準備中。先熟悉設定，公開版本就緒後，這裡會提供下載。',
    requirements: 'Windows 10 / 11 · x64 · WebView2', github: '查看 GitHub 專案', portable: '下載可攜版 (Portable)', back: '回到頂端',
    faqTitle: '開始之前，你可能想知道',
    faq: [
      ['需要哪些額外軟體？', '可攜版需 WebView2 Evergreen Runtime。VST3 外掛與虛擬音訊裝置（例如 VB-CABLE）須自行安裝；使用 ASIO 時也需要硬體對應驅動。'],
      ['一定要有外掛嗎？', '不需要。你可以先設定來源與輸出路由，再加入自己安裝的 VST3 外掛。'],
      ['為什麼是 CABLE Input 接 CABLE Output？', 'RoudaMix 將聲音寫入播放端 CABLE Input；OBS 或 Discord 從錄音端 CABLE Output 讀取。兩個名稱指向同一條虛擬線材的不同端點。'],
      ['會有延遲嗎？', '會。延遲取決於裝置、驅動、緩衝區與外掛。Low Latency 不加入 Compensation Delay，也不保證平行路徑同步；Monitor Bypass 只略過選定外掛。'],
      ['這是 OBS 或 Discord 的直接整合嗎？', '不是。這裡展示透過虛擬音訊裝置傳送聲音的方式。實際名稱可能因軟體版本與語言而異。'],
    ], footer: 'Windows 音訊混音與 VST3 外掛宿主',
  },
  en: {
    nav: ['Explore', 'Quick start', 'Download'], skip: 'Skip to guide', language: '繁體中文',
    eyebrow: 'FOR STREAMERS, CREATORS & EVERY OPEN MIC', hero: ['Your sound.', 'Your routing.'],
    intro: 'Bring your mic, game and voice chat into one workspace. Add your VST3 plugins. Choose what you hear, and what your audience hears.',
    cta: 'Get RoudaMix', explore: 'Follow the sound', availability: 'Windows release coming soon',
    scroll: 'SCROLL TO EXPLORE · ABOUT 1 MIN', signal: ['Microphone', 'Game', 'Voice chat'],
    chapterLabel: 'Workflow chapters', demo: 'Illustrated workflow · not a running app',
    scenes: [
      ['Every sound starts here.', 'Open RoudaMix and give your audio a common starting point. Follow one signal as we build a streaming setup, step by step.', 'Workspace'],
      ['Choose what comes in.', 'In Settings → Audio / Session, select System audio (WASAPI). Add an Audio track and select your microphone. Separate App tracks can capture your game and voice chat.', 'Devices & inputs'],
      ['Make it sound like you.', 'Open the plugin list and add an installed VST3. We use reverb to give the voice some space. Install the plugin separately; this effect is not bundled with RoudaMix.', 'VST3 plugins'],
      ['One source. Two destinations.', 'Route the input to both monitor and stream. Select headphones with Low Latency for monitoring. Send the stream to CABLE Input with Full PDC processing.', 'Two outputs'],
      ['Clarity for you. Atmosphere for them.', 'Enable Monitor Bypass on the reverb. The Low-Latency monitor output skips this plugin, while the stream keeps the effect. Each mix serves its listener.', 'Split & listen'],
      ['Your sound, ready for the stream.', 'Send the RoudaMix stream to CABLE Input. Add Audio Input Capture in OBS and choose CABLE Output as its device. Check the meter to confirm the audio arrives.', 'Connect OBS'],
      ['Keep the conversation going.', 'In Discord → Voice & Video, choose CABLE Output as your input device. Other apps that accept an audio input device can use the same route.', 'Beyond streaming'],
    ],
    monitor: 'Monitor', stream: 'Stream', headphones: 'Headphones', dry: 'Reverb skipped', wet: 'Reverb included',
    audioSoon: 'The two listening samples are being prepared. Keep exploring the illustrated workflow.', play: 'Play sample', pause: 'Pause', audioError: 'The sample could not load. Try again later; the guide remains available.', loading: 'Loading samples…', position: 'Listening position',
    guideLabel: 'QUICK START / GET CONNECTED', guideTitle: 'From your first launch\nto your first stream.', guideIntro: 'Keep this setup nearby. Get every signal to the right destination, one step at a time.',
    steps: [
      ['Extract and launch', 'Once the official Windows x64 release is available, extract the whole archive and run RoudaMix.exe. The portable build needs WebView2 Evergreen Runtime. Keep your data folder when updating.'],
      ['Choose a device and microphone', 'Open Settings → Audio / Session → Device and select System audio (WASAPI), labelled「系統音訊 (WASAPI)」in the app. Press Start if needed. Add an Audio track with「＋ Audio」and select your microphone as input. Use an App track to select a game or voice app that is playing audio.'],
      ['Add your VST3', 'Install a Windows x64 VST3 plugin, then scan for plugins in RoudaMix. Add an effect from the track’s plugin list. Reverb describes our example effect; it is not the name of a bundled plugin.'],
      ['Route the monitor and stream', 'Select both monitor and stream as input-track destinations. Choose your headphones for the monitor output and set its policy to Low Latency. Keep the stream on Full PDC. Enable the plugin’s Monitor Bypass (M) to skip it in your monitor mix.'],
      ['Install and configure VB-CABLE', 'Install VB-CABLE from the official VB-Audio website and restart as instructed. Set the RoudaMix stream output to CABLE Input, the receiving end of the virtual cable.'],
      ['Capture the audio in OBS', 'Add an Audio Input Capture source in OBS and select CABLE Output. Check the meter and make a short test recording. Avoid capturing the same microphone or desktop audio twice. For Discord, select the input device under Voice & Video.'],
    ],
    downloadTitle: 'Your next open mic.\nYour way to sound.', downloadBody: 'The Windows release is being prepared. Explore the setup now; the download will appear here when a public build is ready.',
    requirements: 'Windows 10 / 11 · x64 · WebView2', github: 'View project on GitHub', portable: 'Download Portable version', back: 'Back to top',
    faqTitle: 'A few things before you start',
    faq: [
      ['What else do I need?', 'The portable build needs WebView2 Evergreen Runtime. Install VST3 plugins and virtual audio devices such as VB-CABLE separately. ASIO also requires the appropriate hardware driver.'],
      ['Do I need a plugin?', 'No. Start with your sources and output routing, then add your own installed VST3 plugins when you need them.'],
      ['Why CABLE Input to CABLE Output?', 'RoudaMix writes audio to the playback endpoint, CABLE Input. OBS or Discord reads it from the recording endpoint, CABLE Output. These are opposite ends of the same virtual cable.'],
      ['Is there latency?', 'Yes. Latency depends on devices, drivers, buffers and plugins. Low Latency adds no Compensation Delay and does not guarantee parallel-path alignment. Monitor Bypass only skips the selected plugin.'],
      ['Is this a direct OBS or Discord integration?', 'No. The example sends sound through a virtual audio device. Actual setting names may vary with software version and language.'],
    ], footer: 'Windows audio mixer & VST3 plugin host',
  },
};
