// Generated by scripts/generate-protocol-artifacts.mjs. Do not edit.
export const ERROR_CODES = ["unsupported_version", "bad_frame", "bad_command", "not_running", "already_running", "device_open_failed", "device_lost", "track_not_found", "cycle_detected", "device_busy", "app_not_found", "unsupported_windows", "plugin_not_found", "plugin_load_failed", "plugin_no_editor", "param_not_found", "session_io", "preset_io", "plugin_state_failed", "internal"] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
