// Generated by scripts/generate-protocol-artifacts.mjs. Do not edit.
import { invoke } from "@tauri-apps/api/core";
import type { AudioApp, CaptureDevice, DeviceInfo, EngineStatus, ParamInfo, RenderDevice, Snapshot, Track } from "./types";

export type CommandKind = "ping" | "get_snapshot" | "get_latency_report" | "list_devices" | "list_audio_apps" | "list_render_devices" | "list_capture_devices" | "start" | "stop" | "open_device_panel" | "track_add" | "track_remove" | "track_set" | "track_set_source" | "track_set_dests" | "track_set_output" | "track_set_output_latency_policy" | "track_move" | "start_scan" | "cancel_scan" | "add_plugin" | "remove_plugin" | "move_plugin" | "set_bypass" | "set_monitor_bypass" | "retry_plugin" | "set_param" | "get_params" | "open_editor" | "close_editor" | "save_preset" | "load_preset" | "save_session" | "load_session" | "ensure_system_outputs" | "set_editor_owner" | "shutdown_engine";
export type ErrorCode = "unsupported_version" | "bad_frame" | "bad_command" | "not_running" | "already_running" | "device_open_failed" | "device_lost" | "track_not_found" | "cycle_detected" | "device_busy" | "app_not_found" | "unsupported_windows" | "plugin_not_found" | "plugin_load_failed" | "plugin_no_editor" | "param_not_found" | "session_io" | "preset_io" | "plugin_state_failed" | "internal";
type EmptyCommandKind = "ping" | "get_snapshot" | "get_latency_report" | "list_devices" | "list_audio_apps" | "list_render_devices" | "list_capture_devices" | "stop" | "open_device_panel" | "cancel_scan" | "ensure_system_outputs" | "shutdown_engine";

/** bridge rejection 的結構化形狀(code = engine 錯誤碼或 not_connected/disconnected/timeout) */
export interface CommandError {
  code: string;
  message: string;
}

export function toCommandError(raw: unknown): CommandError {
  if (typeof raw === "object" && raw !== null &&
      typeof (raw as CommandError).code === "string" &&
      typeof (raw as CommandError).message === "string")
    return raw as CommandError;
  return { code: "internal", message: raw instanceof Error ? raw.message : String(raw) };
}

export interface CommandPayloads {
  "ping": Record<string, never>;
  "get_snapshot": Record<string, never>;
  "get_latency_report": Record<string, never>;
  "list_devices": Record<string, never>;
  "list_audio_apps": Record<string, never>;
  "list_render_devices": Record<string, never>;
  "list_capture_devices": Record<string, never>;
  "start": { "deviceKey": string; "sampleRate": number | null; "bufferSize"?: number | null };
  "stop": Record<string, never>;
  "open_device_panel": Record<string, never>;
  "track_add": { "kind": "audio" | "app" | "fx" | "output"; "name"?: string; "color"?: number };
  "track_remove": { "trackId": number };
  "track_set": { "trackId": number; "name"?: string; "color"?: number; "gain"?: number; "mute"?: boolean };
  "track_set_source": { "trackId": number; "source": null | { "type": "sine"; "freq": number } | { "type": "asioIn"; "channel": number; "mono"?: boolean } | { "type": "app"; "pid": number; "name"?: string } | { "type": "wasapiIn"; "deviceId"?: string } };
  "track_set_dests": { "trackId": number; "dests": Array<number> };
  "track_set_output": { "trackId": number; "output": null | { "type": "asioOut"; "channel": number } | { "type": "wasapi"; "deviceId": string } };
  "track_set_output_latency_policy": { "trackId": number; "policy": "fullPdc" | "lowLatency" };
  "track_move": { "trackId": number; "newIndex": number };
  "start_scan": { "roots"?: Array<string> };
  "cancel_scan": Record<string, never>;
  "add_plugin": { "trackId": number; "path": string; "classId"?: string };
  "remove_plugin": { "instanceId": number };
  "move_plugin": { "instanceId": number; "newIndex": number };
  "set_bypass": { "instanceId": number; "bypassed": boolean };
  "set_monitor_bypass": { "instanceId": number; "bypassed": boolean };
  "retry_plugin": { "instanceId": number; "path"?: string };
  "set_param": { "instanceId": number; "paramId": number; "value": number };
  "get_params": { "instanceId": number };
  "open_editor": { "instanceId": number };
  "close_editor": { "instanceId": number };
  "save_preset": { "instanceId": number; "path": string };
  "load_preset": { "instanceId": number; "path": string };
  "save_session": { "path": string | null; "deviceKey"?: string | null; "sampleRate"?: number | null; "bufferSize"?: number | null };
  "load_session": { "path": string };
  "ensure_system_outputs": Record<string, never>;
  "set_editor_owner": { "hwnd": number };
  "shutdown_engine": Record<string, never>;
}

export interface CommandResults {
  "ping": { "engineVersion": string };
  "get_snapshot": { "snapshot": Snapshot };
  "get_latency_report": { "report": { "generation": number; "ok": boolean; "error": string; "bufferBytes": number; "outputs": Array<{ "trackId": number; "totalPluginDelaySamples": number; "compensationDelaySamples": number; "synchronized": boolean }>; "edges": Array<{ "fromTrackId": number; "toTrackId": number; "compensationDelaySamples": number }>; "tracks": Array<Track> } };
  "list_devices": { "devices": Array<DeviceInfo> };
  "list_audio_apps": { "apps": Array<AudioApp> };
  "list_render_devices": { "devices": Array<RenderDevice> };
  "list_capture_devices": { "devices": Array<CaptureDevice> };
  "start": EngineStatus;
  "stop": EngineStatus;
  "open_device_panel": { "panel": boolean };
  "track_add": { "trackId": number; "tracks": Array<Track> };
  "track_remove": { "tracks": Array<Track> };
  "track_set": { "tracks": Array<Track> };
  "track_set_source": { "tracks": Array<Track> };
  "track_set_dests": { "tracks": Array<Track> };
  "track_set_output": { "tracks": Array<Track> };
  "track_set_output_latency_policy": { "tracks": Array<Track> };
  "track_move": { "tracks": Array<Track> };
  "start_scan": { "jobId": number; "reused": boolean };
  "cancel_scan": { "jobId": number; "cancelling": boolean };
  "add_plugin": { "instanceId": number; "trackId": number; "tracks": Array<Track> };
  "remove_plugin": { "tracks": Array<Track> };
  "move_plugin": { "tracks": Array<Track> };
  "set_bypass": { "tracks": Array<Track> };
  "set_monitor_bypass": { "tracks": Array<Track> };
  "retry_plugin": { "instanceId": number; "tracks": Array<Track> };
  "set_param": Record<string, never>;
  "get_params": { "instanceId": number; "params": Array<ParamInfo> };
  "open_editor": { "instanceId": number; "editor": boolean };
  "close_editor": Record<string, never>;
  "save_preset": { "savedPath": string };
  "load_preset": { "tracks": Array<Track> };
  "save_session": { "savedPath": string; "revision": number };
  "load_session": { "revision": number; "deviceKey"?: string | null; "sampleRate"?: number | null; "bufferSize"?: number | null; "missing"?: Array<Record<string, unknown>> };
  "ensure_system_outputs": { "tracks": Array<Track>; "revision": number };
  "set_editor_owner": Record<string, never>;
  "shutdown_engine": Record<string, never>;
}

export interface CommandErrors {
  "ping": never;
  "get_snapshot": never;
  "get_latency_report": never;
  "list_devices": never;
  "list_audio_apps": never;
  "list_render_devices": never;
  "list_capture_devices": never;
  "start": "already_running" | "device_open_failed";
  "stop": never;
  "open_device_panel": "not_running";
  "track_add": "bad_command";
  "track_remove": "track_not_found";
  "track_set": "bad_command";
  "track_set_source": "bad_command" | "track_not_found" | "app_not_found" | "unsupported_windows" | "device_busy";
  "track_set_dests": "bad_command" | "track_not_found" | "cycle_detected" | "plugin_state_failed";
  "track_set_output": "bad_command" | "track_not_found" | "device_busy";
  "track_set_output_latency_policy": "bad_command";
  "track_move": "bad_command";
  "start_scan": never;
  "cancel_scan": never;
  "add_plugin": "plugin_load_failed";
  "remove_plugin": "plugin_not_found" | "plugin_state_failed" | "bad_command";
  "move_plugin": "bad_command";
  "set_bypass": "plugin_not_found" | "plugin_state_failed" | "bad_command";
  "set_monitor_bypass": "plugin_not_found" | "plugin_state_failed" | "bad_command";
  "retry_plugin": "plugin_not_found" | "plugin_load_failed" | "bad_command";
  "set_param": "param_not_found";
  "get_params": "plugin_not_found";
  "open_editor": "plugin_not_found" | "plugin_no_editor";
  "close_editor": "plugin_not_found";
  "save_preset": "plugin_not_found" | "preset_io";
  "load_preset": "plugin_not_found" | "preset_io" | "plugin_state_failed";
  "save_session": "session_io";
  "load_session": "session_io";
  "ensure_system_outputs": never;
  "set_editor_owner": never;
  "shutdown_engine": never;
}

export function engineCommand<K extends CommandKind>(
  kind: K,
  ...args: K extends EmptyCommandKind
    ? [payload?: CommandPayloads[K]]
    : [payload: CommandPayloads[K]]
): Promise<CommandResults[K]> {
  return invoke<CommandResults[K]>("engine_command", { kind, payload: args[0] ?? {} }).catch(
    (raw: unknown) => {
      throw toCommandError(raw);
    },
  );
}
